KNOWN_CLIENT_MOD_REGEX = [
    r"(?i).*optifine.*\\.jar$",
    r"(?i).*iris.*\\.jar$",
    r"(?i).*sodium.*\\.jar$",
    r"(?i).*journeymap.*\\.jar$",
    r"(?i).*xaeros.*\\.jar$",
    r"(?i).*inventory.*hud.*\\.jar$",
    r"(?i).*damagetilt.*\\.jar$",
    r"(?i).*rei.*\\.jar$",
    r"(?i).*jei.*\\.jar$",
]

COMMON_JVM_PARAMS = [
    "-server",
    "-XX:+AlwaysPreTouch",
    "-XX:+ExplicitGCInvokesConcurrent",
    "-XX:NmethodSweepActivity=1",
    "-XX:NodeLimitFudgeFactor=8000",
    "-XX:MaxNodeLimit=240000",
    "-XX:-DontCompileHugeMethods",
    "-XX:+PerfDisableSharedMem",
    "-XX:+AlwaysActAsServerClassMachine",
    "-XX:+UnlockDiagnosticVMOptions",
    "-XX:+UseCompressedOops",
    "-XX:+UseNUMA",
    "-XX:MaxInlineLevel=20",
    "-XX:FreqInlineSize=325",
    "-XX:MaxInlineSize=75",
    "-XX:InlineSmallCode=2500",
    "-XX:MaxRecursiveInlineLevel=2",
    "-XX:ParallelGCThreads=6",
    "-Dsun.rmi.dgc.server.gcInterval=3600000",
    "-Dfml.ignorePatchDiscrepancies=true",
    "-Dfml.ignoreInvalidMinecraftCertificates=true",
    "-Dfml.readTimeout=90",
    "-Dfile.encoding=UTF-8",
]

JVM_PARAMS_DW8 = [
    "-XX:+UseG1GC",
    "-XX:+ParallelRefProcEnabled",
    "-XX:ReservedCodeCacheSize=350M",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:MaxGCPauseMillis=200",
    "-XX:G1NewSizePercent=30",
    "-XX:G1MaxNewSizePercent=40",
    "-XX:G1HeapRegionSize=16M",
    "-XX:G1ReservePercent=20",
    "-XX:G1HeapWastePercent=5",
    "-XX:G1MixedGCCountTarget=4",
    "-XX:InitiatingHeapOccupancyPercent=15",
    "-XX:G1MixedGCLiveThresholdPercent=90",
    "-XX:G1RSetUpdatingPauseTimePercent=5",
    "-XX:SurvivorRatio=32",
    "-XX:MaxTenuringThreshold=1",
]

JVM_PARAMS_DW11 = [
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:ReservedCodeCacheSize=400M",
    "-XX:NonNMethodCodeHeapSize=12M",
    "-XX:ProfiledCodeHeapSize=194M",
    "-XX:NonProfiledCodeHeapSize=194M",
    "-XX:+UseVectorCmov",
    "-XX:+UseFastUnorderedTimeStamps",
    "-XX:ThreadPriorityPolicy=1",
    "-XX:AllocatePrefetchStyle=3",
    "-XX:+UseVtableBasedCHA",
    "-Dcom.alibaba.enableFastSerialization=true",
    "-XX:+UseBigDecimalOpt",
    "-XX:+ReduceNMethodSize",
    "-XX:+UseG1GC",
    "-XX:MaxGCPauseMillis=80",
    "-XX:G1NewSizePercent=28",
    "-XX:G1HeapRegionSize=16M",
    "-XX:G1ReservePercent=20",
    "-XX:G1MixedGCCountTarget=3",
    "-XX:InitiatingHeapOccupancyPercent=40",
    "-XX:G1MixedGCLiveThresholdPercent=90",
    "-XX:G1RSetUpdatingPauseTimePercent=0",
    "-XX:SurvivorRatio=32",
    "-XX:MaxTenuringThreshold=1",
    "-XX:G1SATBBufferEnqueueingThresholdPercent=30",
    "-XX:G1ConcMarkStepDurationMillis=5",
    "-XX:G1ConcRefinementServiceIntervalMillis=150",
    "-XX:G1ConcRSHotCardLimit=16",
    "-XX:+UseCompactObjectHeaders",
    "-XX:-DontCompactNormalPitches",
]

JVM_PARAMS_GRAALVM17 = [
    "-XX:+UseZGC",
    "-XX:-ZProactive",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:ReservedCodeCacheSize=400M",
    "-XX:NonNMethodCodeHeapSize=12M",
    "-XX:ProfiledCodeHeapSize=194M",
    "-XX:NonProfiledCodeHeapSize=194M",
    "-XX:AllocatePrefetchStyle=1",
    "-XX:+EagerJVMCI",
    "-XX:+UseStringDeduplication",
    "-XX:+UseFastStosb",
    "-XX:+UseNewLongLShift",
    "-XX:+UseVectorCmov",
    "-XX:+UseXmmI2D",
    "-XX:+UseXmmI2F",
    "-XX:+AlignVector",
    "-XX:+OptimizeFill",
    "-XX:+EnableVectorSupport",
    "-XX:+UseCharacterCompareIntrinsics",
    "-XX:+UseVectorStubs",
    "-XX:UseAVX=2",
    "-XX:UseSSE=4",
    "-XX:+IgnoreUnrecognizedVMOptions",
    "-XX:+DisableExplicitGC",
    "-XX:ThreadPriorityPolicy=1",
    "-XX:+UseJVMCICompiler",
    "-XX:+TrustFinalNonStaticFields",
    "-XX:+AllowParallelDefineClass",
    "-XX:+UseCriticalJavaThreadPriority",
    "-XX:+OptoBundling",
    "-XX:+OptoScheduling",
    "-XX:+AlwaysCompileLoopMethods",
    "-XX:+EnableVectorAggressiveReboxing",
    "-XX:+UseBiasedLocking",
    "-Dgraal.UsePriorityInlining=true",
    "-Dgraal.Vectorization=true",
    "-Dgraal.DetectInvertedLoopsAsCounted=true",
    "-Dgraal.LoopInversion=true",
    "-Dgraal.VectorizeHashes=true",
    "-Dgraal.EnterprisePartialUnroll=true",
    "-Dgraal.VectorizeSIMD=true",
    "-Dgraal.TuneInlinerExploration=1",
    "-Dgraal.LoopRotation=true",
    "-Dgraal.OptWriteMotion=true",
    "-Dgraal.CompilerConfiguration=enterprise",
    "-Dgraal.SpectrePHTBarriers=None",
    "-Dgraal.WriteableCodeCache=true",
    "-Dgraal.BaseTargetSpending=160",
    "-Dlog4j2.formatMsgNoLookups=true",
    "-Djdk.lang.Process.allowAmbiguousCommands=true",
]

JVM_PARAMS_GRAALVM25 = [
    "-XX:+UseZGC",
    "-XX:-ZProactive",
    "-XX:+UnlockExperimentalVMOptions",
    "-XX:ReservedCodeCacheSize=400M",
    "-XX:NonNMethodCodeHeapSize=12M",
    "-XX:ProfiledCodeHeapSize=194M",
    "-XX:NonProfiledCodeHeapSize=194M",
    "-XX:AllocatePrefetchStyle=1",
    "-XX:+EagerJVMCI",
    "-XX:+UseStringDeduplication",
    "-XX:+UseFastStosb",
    "-XX:+UseNewLongLShift",
    "-XX:+UseVectorCmov",
    "-XX:+UseXmmI2D",
    "-XX:+UseXmmI2F",
    "-XX:+AlignVector",
    "-XX:+OptimizeFill",
    "-XX:+EnableVectorSupport",
    "-XX:+UseCharacterCompareIntrinsics",
    "-XX:+UseVectorStubs",
    "-XX:UseAVX=2",
    "-XX:UseSSE=4",
    "-Djdk.graal.UsePriorityInlining=true",
    "-Djdk.graal.Vectorization=true",
    "-Djdk.graal.DetectInvertedLoopsAsCounted=true",
    "-Djdk.graal.LoopInversion=true",
    "-Djdk.graal.VectorizeHashes=true",
    "-Djdk.graal.EnterprisePartialUnroll=true",
    "-Djdk.graal.VectorizeSIMD=true",
    "-Djdk.graal.TuneInlinerExploration=1",
    "-Djdk.graal.LoopRotation=true",
    "-Djdk.graal.CompilerConfiguration=enterprise",
    "-XX:+IgnoreUnrecognizedVMOptions",
    "-XX:+DisableExplicitGC",
    "-XX:+AllowParallelDefineClass",
    "-XX:+AlwaysCompileLoopMethods",
    "-XX:+OptoBundling",
    "-XX:+OptoScheduling",
    "-XX:+TrustFinalNonStaticFields",
    "-Dlog4j2.formatMsgNoLookups=true",
    "-Djdk.lang.Process.allowAmbiguousCommands=true",
    "-Djdk.graal.SpectrePHTBarriers=None",
]

SUPPORTED_JAVA_VERSIONS = [8, 11, 17, 21, 25]

JAVA_VERSION_TO_JVM_PARAMS = {
    8: [*COMMON_JVM_PARAMS, *JVM_PARAMS_DW8],  # Java 8 使用龙井（Dragonwell）参数
    11: [*COMMON_JVM_PARAMS, *JVM_PARAMS_DW11],  # Java 11 使用龙井（Dragonwell）参数
    17: [*COMMON_JVM_PARAMS, *JVM_PARAMS_GRAALVM17],  # Java 17 使用 GraalVM 参数
    21: [*COMMON_JVM_PARAMS, *JVM_PARAMS_GRAALVM17],  # Java 21 按要求复用 GraalVM 17 参数
    25: [*COMMON_JVM_PARAMS, *JVM_PARAMS_GRAALVM25],  # Java 25 使用 GraalVM 参数
}


def get_jvm_params_for_java_version(version: int) -> list[str]:
    """按 Java 主版本返回预置 JVM 参数，不支持时默认回退到 Java 21 档位。"""
    return list(JAVA_VERSION_TO_JVM_PARAMS.get(version, JAVA_VERSION_TO_JVM_PARAMS[21]))
